// Auto-generated by: supabase gen types typescript --local > src/types/supabase.ts
// Run /gen-types after pushing migrations to regenerate this file.
// Do not edit by hand.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          username: string
          display_name: string | null
          avatar_url: string | null
          bio: string | null
          discord_tag: string | null
          role: 'member' | 'moderator' | 'admin'
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          username: string
          display_name?: string | null
          avatar_url?: string | null
          bio?: string | null
          discord_tag?: string | null
          role?: 'member' | 'moderator' | 'admin'
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          username?: string
          display_name?: string | null
          avatar_url?: string | null
          bio?: string | null
          discord_tag?: string | null
          role?: 'member' | 'moderator' | 'admin'
          is_active?: boolean
          updated_at?: string
        }
        Relationships: []
      }
      games: {
        Row: {
          id: string
          name: string
          slug: string
          logo_url: string | null
          cover_url: string | null
          current_patch: string | null
          is_supported: boolean
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          logo_url?: string | null
          cover_url?: string | null
          current_patch?: string | null
          is_supported?: boolean
          sort_order?: number
        }
        Update: {
          name?: string
          slug?: string
          logo_url?: string | null
          cover_url?: string | null
          current_patch?: string | null
          is_supported?: boolean
          sort_order?: number
          updated_at?: string
        }
        Relationships: []
      }
      user_games: {
        Row: {
          id: string
          user_id: string
          game_id: string
          in_game_name: string | null
          current_rank: string | null
          peak_rank: string | null
          is_primary: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          game_id: string
          in_game_name?: string | null
          current_rank?: string | null
          peak_rank?: string | null
          is_primary?: boolean
        }
        Update: {
          in_game_name?: string | null
          current_rank?: string | null
          peak_rank?: string | null
          is_primary?: boolean
        }
        Relationships: [
          { foreignKeyName: 'user_games_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
          { foreignKeyName: 'user_games_game_id_fkey'; columns: ['game_id']; isOneToOne: false; referencedRelation: 'games'; referencedColumns: ['id'] }
        ]
      }
      news_posts: {
        Row: {
          id: string
          title: string
          slug: string
          body: string
          excerpt: string | null
          cover_url: string | null
          author_id: string | null
          category: 'news' | 'announcement' | 'patch' | 'strategy' | 'event'
          game_id: string | null
          tags: string[]
          is_published: boolean
          is_pinned: boolean
          views: number
          published_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          slug: string
          body: string
          excerpt?: string | null
          cover_url?: string | null
          author_id?: string | null
          category?: 'news' | 'announcement' | 'patch' | 'strategy' | 'event'
          game_id?: string | null
          tags?: string[]
          is_published?: boolean
          is_pinned?: boolean
          views?: number
          published_at?: string | null
        }
        Update: {
          title?: string
          slug?: string
          body?: string
          excerpt?: string | null
          cover_url?: string | null
          author_id?: string | null
          category?: 'news' | 'announcement' | 'patch' | 'strategy' | 'event'
          game_id?: string | null
          tags?: string[]
          is_published?: boolean
          is_pinned?: boolean
          views?: number
          published_at?: string | null
          updated_at?: string
        }
        Relationships: [
          { foreignKeyName: 'news_posts_author_id_fkey'; columns: ['author_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
          { foreignKeyName: 'news_posts_game_id_fkey'; columns: ['game_id']; isOneToOne: false; referencedRelation: 'games'; referencedColumns: ['id'] }
        ]
      }
      team_roster: {
        Row: {
          id: string
          user_id: string
          game_id: string
          in_game_role: string | null
          jersey_number: number | null
          is_captain: boolean
          is_active: boolean
          joined_at: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          game_id: string
          in_game_role?: string | null
          jersey_number?: number | null
          is_captain?: boolean
          is_active?: boolean
          joined_at?: string
        }
        Update: {
          in_game_role?: string | null
          jersey_number?: number | null
          is_captain?: boolean
          is_active?: boolean
          joined_at?: string
        }
        Relationships: [
          { foreignKeyName: 'team_roster_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
          { foreignKeyName: 'team_roster_game_id_fkey'; columns: ['game_id']; isOneToOne: false; referencedRelation: 'games'; referencedColumns: ['id'] }
        ]
      }
      club_members: {
        Row: {
          id: string
          user_id: string
          panel_role: string | null
          is_founder: boolean
          bio: string | null
          joined_at: string
          sort_order: number
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          panel_role?: string | null
          is_founder?: boolean
          bio?: string | null
          joined_at?: string
          sort_order?: number
        }
        Update: {
          panel_role?: string | null
          is_founder?: boolean
          bio?: string | null
          joined_at?: string
          sort_order?: number
        }
        Relationships: [
          { foreignKeyName: 'club_members_user_id_fkey'; columns: ['user_id']; isOneToOne: true; referencedRelation: 'profiles'; referencedColumns: ['id'] }
        ]
      }
      tournaments: {
        Row: {
          id: string
          game_id: string
          name: string
          description: string | null
          cover_url: string | null
          format: 'single_elimination' | 'double_elimination' | 'round_robin' | 'swiss'
          status: 'upcoming' | 'registration' | 'ongoing' | 'completed' | 'cancelled'
          max_teams: number | null
          prize_pool: string | null
          rules_url: string | null
          stream_url: string | null
          registration_open: boolean
          start_date: string | null
          end_date: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          game_id: string
          name: string
          description?: string | null
          cover_url?: string | null
          format?: 'single_elimination' | 'double_elimination' | 'round_robin' | 'swiss'
          status?: 'upcoming' | 'registration' | 'ongoing' | 'completed' | 'cancelled'
          max_teams?: number | null
          prize_pool?: string | null
          rules_url?: string | null
          stream_url?: string | null
          registration_open?: boolean
          start_date?: string | null
          end_date?: string | null
          created_by?: string | null
        }
        Update: {
          game_id?: string
          name?: string
          description?: string | null
          cover_url?: string | null
          format?: 'single_elimination' | 'double_elimination' | 'round_robin' | 'swiss'
          status?: 'upcoming' | 'registration' | 'ongoing' | 'completed' | 'cancelled'
          max_teams?: number | null
          prize_pool?: string | null
          rules_url?: string | null
          stream_url?: string | null
          registration_open?: boolean
          start_date?: string | null
          end_date?: string | null
          updated_at?: string
        }
        Relationships: [
          { foreignKeyName: 'tournaments_game_id_fkey'; columns: ['game_id']; isOneToOne: false; referencedRelation: 'games'; referencedColumns: ['id'] },
          { foreignKeyName: 'tournaments_created_by_fkey'; columns: ['created_by']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] }
        ]
      }
      tournament_teams: {
        Row: {
          id: string
          tournament_id: string
          team_name: string
          captain_id: string | null
          status: 'pending' | 'approved' | 'rejected' | 'disqualified'
          registered_at: string
        }
        Insert: {
          id?: string
          tournament_id: string
          team_name: string
          captain_id?: string | null
          status?: 'pending' | 'approved' | 'rejected' | 'disqualified'
        }
        Update: {
          team_name?: string
          captain_id?: string | null
          status?: 'pending' | 'approved' | 'rejected' | 'disqualified'
        }
        Relationships: [
          { foreignKeyName: 'tournament_teams_tournament_id_fkey'; columns: ['tournament_id']; isOneToOne: false; referencedRelation: 'tournaments'; referencedColumns: ['id'] },
          { foreignKeyName: 'tournament_teams_captain_id_fkey'; columns: ['captain_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] }
        ]
      }
      tournament_team_members: {
        Row: {
          id: string
          team_id: string
          user_id: string
        }
        Insert: {
          id?: string
          team_id: string
          user_id: string
        }
        Update: {
          team_id?: string
          user_id?: string
        }
        Relationships: [
          { foreignKeyName: 'ttm_team_id_fkey'; columns: ['team_id']; isOneToOne: false; referencedRelation: 'tournament_teams'; referencedColumns: ['id'] },
          { foreignKeyName: 'ttm_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] }
        ]
      }
      matches: {
        Row: {
          id: string
          tournament_id: string
          round: number
          match_number: number
          team1_id: string | null
          team2_id: string | null
          team1_score: number | null
          team2_score: number | null
          winner_id: string | null
          vod_url: string | null
          played_at: string | null
          status: 'scheduled' | 'live' | 'completed' | 'forfeit'
          created_at: string
        }
        Insert: {
          id?: string
          tournament_id: string
          round: number
          match_number: number
          team1_id?: string | null
          team2_id?: string | null
          team1_score?: number | null
          team2_score?: number | null
          winner_id?: string | null
          vod_url?: string | null
          played_at?: string | null
          status?: 'scheduled' | 'live' | 'completed' | 'forfeit'
        }
        Update: {
          team1_id?: string | null
          team2_id?: string | null
          team1_score?: number | null
          team2_score?: number | null
          winner_id?: string | null
          vod_url?: string | null
          played_at?: string | null
          status?: 'scheduled' | 'live' | 'completed' | 'forfeit'
        }
        Relationships: [
          { foreignKeyName: 'matches_tournament_id_fkey'; columns: ['tournament_id']; isOneToOne: false; referencedRelation: 'tournaments'; referencedColumns: ['id'] }
        ]
      }
      player_stats: {
        Row: {
          id: string
          user_id: string
          game_id: string
          wins: number
          losses: number
          draws: number
          rank_points: number
          season: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          game_id: string
          wins?: number
          losses?: number
          draws?: number
          rank_points?: number
          season?: string
        }
        Update: {
          wins?: number
          losses?: number
          draws?: number
          rank_points?: number
          season?: string
          updated_at?: string
        }
        Relationships: [
          { foreignKeyName: 'player_stats_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
          { foreignKeyName: 'player_stats_game_id_fkey'; columns: ['game_id']; isOneToOne: false; referencedRelation: 'games'; referencedColumns: ['id'] }
        ]
      }
      membership_applications: {
        Row: {
          id: string
          user_id: string | null
          full_name: string
          email: string
          discord_tag: string | null
          motivation: string
          preferred_games: string[] | null
          experience: string | null
          availability: string | null
          status: 'pending' | 'approved' | 'rejected'
          reviewed_by: string | null
          reviewed_at: string | null
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          full_name: string
          email: string
          discord_tag?: string | null
          motivation: string
          preferred_games?: string[] | null
          experience?: string | null
          availability?: string | null
          status?: 'pending' | 'approved' | 'rejected'
        }
        Update: {
          status?: 'pending' | 'approved' | 'rejected'
          reviewed_by?: string | null
          reviewed_at?: string | null
          notes?: string | null
        }
        Relationships: []
      }
      site_settings: {
        Row: {
          key: string
          value: Json
          updated_by: string | null
          updated_at: string
        }
        Insert: {
          key: string
          value: Json
          updated_by?: string | null
        }
        Update: {
          value?: Json
          updated_by?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      audit_log: {
        Row: {
          id: string
          actor_id: string | null
          action: string
          target_type: string | null
          target_id: string | null
          metadata: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          actor_id?: string | null
          action: string
          target_type?: string | null
          target_id?: string | null
          metadata?: Json | null
        }
        Update: {
          actor_id?: string | null
          action?: string
          target_type?: string | null
          target_id?: string | null
          metadata?: Json | null
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: {
      increment_post_views: {
        Args: { post_id: string }
        Returns: undefined
      }
      is_admin: {
        Args: Record<string, never>
        Returns: boolean
      }
      is_mod: {
        Args: Record<string, never>
        Returns: boolean
      }
    }
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
